'use client';
import {useEffect,useRef,useState} from 'react';
import type * as Leaflet from 'leaflet';
import 'leaflet/dist/leaflet.css';
import {LocateFixed,Plus,Minus} from 'lucide-react';
import {categories,region,type Place} from './places';
// Provider adapter: other application components use provider-independent Place coordinates.
export default function MapView({places,onSelect}:{places:Place[];onSelect:(p:Place)=>void}){
const container=useRef<HTMLDivElement>(null),map=useRef<Leaflet.Map|null>(null),lib=useRef<typeof Leaflet|null>(null),layer=useRef<Leaflet.LayerGroup|null>(null);const [loaded,setLoaded]=useState(false),[error,setError]=useState(false);
useEffect(()=>{let disposed=false;let observer:ResizeObserver|undefined;import('leaflet').then(L=>{if(disposed||!container.current)return;lib.current=L;const m=L.map(container.current,{zoomControl:false,minZoom:14,maxZoom:18,maxBounds:region.bounds,maxBoundsViscosity:1}).setView(region.center,region.zoom);map.current=m;L.tileLayer('https://tile.openstreetmap.org/{z}/{x}/{y}.png',{attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a>',maxZoom:19}).on('tileerror',()=>setError(true)).on('tileload',()=>setError(false)).addTo(m);layer.current=L.layerGroup().addTo(m);setLoaded(true);observer=new ResizeObserver(()=>m.invalidateSize());observer.observe(container.current)}).catch(()=>setError(true));return()=>{disposed=true;observer?.disconnect();map.current?.remove();map.current=null}},[]);
useEffect(()=>{if(!loaded||!lib.current||!layer.current)return;const L=lib.current;layer.current.clearLayers();for(const p of places){const c=categories.find(c=>c.id===p.category)!;const node=document.createElement('div');node.className='map-pin';node.style.setProperty('--pin-color',c.color);const symbol=document.createElement('span');symbol.className='pin-symbol';symbol.textContent=({food:'☕',party:'♫',taxi:'T',walk:'↟',fun:'✦'} as Record<string,string>)[p.category];const label=document.createElement('strong');label.textContent=p.name;node.appendChild(symbol);node.appendChild(label);L.marker([p.lat,p.lng],{icon:L.divIcon({html:node,className:'custom-marker',iconSize:[150,44],iconAnchor:[20,44]}),title:p.name,keyboard:true}).on('click',()=>onSelect(p)).addTo(layer.current);if(p.category==='walk')L.polyline([[40.9425,38.214],[40.9429,38.221],[40.9432,38.229],[40.944,38.233]],{color:'#33855e',weight:5,dashArray:'7 8'}).addTo(layer.current)}},[loaded,places,onSelect]);
return <><div ref={container} className="leaflet-surface"/>{error&&<div className="map-error" role="status">Harita yüklenemedi. Bağlantını kontrol et; yer listesi kullanılabilir.</div>}<div className="map-controls"><button aria-label="Yakınlaştır" onClick={()=>map.current?.zoomIn()}><Plus size={20}/></button><button aria-label="Uzaklaştır" onClick={()=>map.current?.zoomOut()}><Minus size={20}/></button><button aria-label="Bulancak merkezine dön" onClick={()=>map.current?.setView(region.center,region.zoom)}><LocateFixed size={20}/></button></div></>}

